import Thumb from "../../../assets/images/zvezdeGrandaEmisije.jpg"
export const programskaShema = [

    {
        day: "2021-05-10",
        sema: [
            {
                time:"00:00",
                title: "Muzicki mix premijera 1",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"03:00",
                title: "Halo halo repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"05:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"08:30",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"09:00",
                title: "Halo halo repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,

            },
            {
                time:"11:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"11:40",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"12:00",
                title: "Grand news",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: true,
            },
            {
                time:"15:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"18:00",
                title: "GRAND news premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"18:30",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"20:00",
                title: "Pesmom za dusu live",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"22:00",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"22:30",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
        ]
    },
    {
        day: "2021-05-11",
        sema: [
            {
                time:"00:00",
                title: "Muzicki mix premijera 2",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"03:00",
                title: "Halo halo repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"05:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"08:30",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"09:00",
                title: "Halo halo repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,

            },
            {
                time:"11:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"11:40",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"12:00",
                title: "Grand news",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: true,
            },
            {
                time:"15:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"18:00",
                title: "GRAND news premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"18:30",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"20:00",
                title: "Pesmom za dusu live",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"22:00",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"22:30",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
        ]
    },
    {
        day: "2021-05-12",
        sema: [
            {
                time:"00:00",
                title: "Muzicki mix premijera 3",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"03:00",
                title: "Halo halo repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"05:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"08:30",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"09:00",
                title: "Halo halo repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,

            },
            {
                time:"11:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"11:40",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"12:00",
                title: "Grand news",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: true,
            },
            {
                time:"15:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"18:00",
                title: "GRAND news premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"18:30",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"20:00",
                title: "Pesmom za dusu live",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"22:00",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"22:30",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
        ]
    },
    {
        day: "2021-05-13",
        sema: [
            {
                time:"00:00",
                title: "Muzicki mix premijerav 4",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"03:00",
                title: "Halo halo repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"05:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"08:30",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"09:00",
                title: "Halo halo repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,

            },
            {
                time:"11:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"11:40",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"12:00",
                title: "Grand news",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: true,
            },
            {
                time:"15:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"18:00",
                title: "GRAND news premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"18:30",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"20:00",
                title: "Pesmom za dusu live",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"22:00",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"22:30",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
        ]
    },
    {
        day: "2021-05-14",
        sema: [
            {
                time:"00:00",
                title: "Muzicki mix premijera 5",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"03:00",
                title: "Halo halo repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"05:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"08:30",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"09:00",
                title: "Halo halo repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,

            },
            {
                time:"11:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"11:40",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"12:00",
                title: "Grand news",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: true,
            },
            {
                time:"15:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"18:00",
                title: "GRAND news premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"18:30",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"20:00",
                title: "Pesmom za dusu live",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"22:00",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"22:30",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
        ]
    },
    {
        day: "2021-05-15",
        sema: [
            {
                time:"00:00",
                title: "Muzicki mix premijera 6",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"03:00",
                title: "Halo halo repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"05:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"08:30",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"09:00",
                title: "Halo halo repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,

            },
            {
                time:"11:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"11:40",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"12:00",
                title: "Grand news",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: true,
            },
            {
                time:"15:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"18:00",
                title: "GRAND news premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"18:30",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"20:00",
                title: "Pesmom za dusu live",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"22:00",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"22:30",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
        ]
    },
    {
        day: "2021-05-16",
        sema: [
            {
                time:"00:00",
                title: "Muzicki mix premijera 7",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"03:00",
                title: "Halo halo repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"05:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"08:30",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"09:00",
                title: "Halo halo repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,

            },
            {
                time:"11:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"11:40",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"12:00",
                title: "Grand news",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: true,
            },
            {
                time:"15:00",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"18:00",
                title: "GRAND news premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"18:30",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"20:00",
                title: "Pesmom za dusu live",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"22:00",
                title: "GRAND news repriza",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
            {
                time:"22:30",
                title: "Muzicki mix premijera",
                info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At eos molestias voluptas. Consectetur corporis deserunt est fuga nesciunt sed, sunt?",
                thumbnail:Thumb,
                live: false,
            },
        ]
    }
]